apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: greenopsinc/argo-server:3.3.8
          imagePullPolicy: Never
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args:
            - server
            - --namespaced
            - --auth-mode
            - sso
            - --auth-mode
            - client
            - --access-control-allow-origin
            - "*"
          env: []
          ports:
            - name: web
              containerPort: 2746
          readinessProbe:
            httpGet:
              port: 2746
              scheme: HTTPS
              path: /
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      hostAliases:
        - hostnames:
            - argocd.apps.argoproj.io
          ip: 192.168.64.5
        - hostnames:
            - workflows.apps.argoproj.io
          ip: 127.0.0.1
      volumes:
        - name: tmp
          emptyDir: { }
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
